#!/usr/bin/python3.6

def over_budget(budget,food_bill,electricity_bill,internet_bill,rent):
  if budget < (food_bill + electricity_bill + internet_bill + rent):
    return True
  else:
    return False
